= Backup and Restore Data In Couchbase Database

Backing up data for a Couchbase database is an essential part of Disaster Recovery plan. This ensures that the data can be restored to the last backup in case of a disaster. This quick start guide will show how to backup and restore data in Couchbase database.

Complete details about the features covered in this guide is at https://developer.couchbase.com/documentation/server/current/backup-restore/backup-restore.html[Backup and Restore].

This guide will use a https://github.com/couchbase-guides/couchbase-amazon-cli[Couchbase install on Amazon EC2] to show backup and restore.

== Backup Data in Couchbase Server

. Create a directory that will store backup data: `sudo mkdir -p /var/lib/couchbase/backups`
. Give write perms to the directory: `sudo chmod 777 /var/lib/couchbase/backups`
. Backup one bucket on the cluster:
+
```
/opt/couchbase/bin/cbbackup \
    http://localhost:8091 \
    /var/lib/couchbase/backups/ \
    -u Administrator \
    -p password \
    -b twitter
```
+
.. `cbbackup` is the tool used to perform the backup
.. Host/port defines the source of backup. Specifying `localhost` here is fine since we are running the backup command on the host where Couchbase is installed. Alternatively, this command can be run from another machine. In that case, the correct host/port needs to be specified.
.. `-u` option is used to specify the admin user name
.. `-p` option is used to specify the admin password
.. `-b` option is used to specify the bucket name, `twitter` in this case
+
The first run of this command will perform a full backup because `/var/lib/couchbase/backups/` directory is empty to begin with. Subsequent runs of this command will perform incremental backups.
+
In addition, this tool can perform backups in the following different ways:
+
.. Backup all buckets in an entire cluster. This is the default option when no bucket is specified.
+
```
/opt/couchbase/bin/cbbackup \
    http://<any-node-ip>:8091 \
    /var/lib/couchbase/backups/ \
    -u Administrator \
    -p password
```
+
.. Backup all buckets on a single node in cluster by using `--single-node` option.
+
```
/opt/couchbase/bin/cbbackup \
    http://<single-node-ip>:8091 \
    /var/lib/couchbase/backups/ \
    -u Administrator \
    -p password \
    --single-node
```
+
.. Backup one named bucket on a specified node
+
```
/opt/couchbase/bin/cbbackup \
    http://<single-node-ip>:8091 \
    /var/lib/couchbase/backups/ \
    -u Administrator \
    -p password \
    --single-node \
    -b <bucket>
```

Full, incremental and cumulative backups can be performed using `-m` option.

== Optional Upload to S3

Keeping the backup data on the same host introduces a Single Point of Failure. Its recommended to save the backup data on a remote drive, such as S3.

Create a zipped archive of the backup tagged by year, month, day, hour, minute and seconds. Upload the archive to S3:

```
filename=twitter-backups-`date +%Y-%m-%d-%H-%M-%S`.tar.gz
sudo tar czvf $filename /var/lib/couchbase/backups/
s3cmd put twitter-backups.tar.gz s3://arungupta.me/
```

Add these commands in a script. Copy that script in `/etc/cron.daily` directory to set it up as a daily cron job. More details about downloading, installing and confiuring `s3cmd` are available at http://s3tools.org/s3cmd.

== Restore Data to Couchbase Server

You may like to restore this data to a local development server.

Restore: https://developer.couchbase.com/documentation/server/current/cli/cbrestore-tool.html

For Couchbase Server Enterprise Edition, use https://developer.couchbase.com/documentation/server/current/backup-restore/enterprise-backup-restore.html[cbbackupmgr].

