= Backup Data in Couchbase Database

Backing up data for a Couchbase database is an essential part of Disaster Recovery plan. This ensures that the data can be restored to the last backup in case of a disaster. This quick start guide will show how to backup data using Couchbase Community Edition. https://github.com/couchbase-guides/couchbase-restore[Another guide] shows how to restore data to a Couchbase server.

The https://developer.couchbase.com/documentation/server/current/backup-restore/backup-restore.html[cbbackup] tool in Couchbase Community Edition will be used in this guide.

In addition, Couchbase Enterprise Edition also has the `cbbackupmgr` tool. Complete details about this tool is at https://developer.couchbase.com/documentation/server/current/backup-restore/enterprise-backup-restore.html[cbbackupmgr].

For this guide, Couchbase server is installed using https://github.com/couchbase-guides/couchbase-amazon-cli[Couchbase install on Amazon EC2].

Let's take backup of the data first.

. Create a directory that will store backup data: `sudo mkdir -p /var/lib/couchbase/backups`
. Give write perms to the directory: `sudo chmod 777 /var/lib/couchbase/backups`

== Backup one bucket in cluster

The `cbbackup` tool allows to backup single bucket from the cluster.

Backup one bucket on the cluster:

```
/opt/couchbase/bin/cbbackup \
    http://localhost:8091 \
    /var/lib/couchbase/backups/ \
    -u Administrator \
    -p password \
    -b twitter
```

. `cbbackup` is the tool used to perform the backup
. Host/port defines the source of backup. Specifying `localhost` here is fine since we are running the backup command on the host where Couchbase is installed. Alternatively, this command can be run from another machine. In that case, the correct host/port needs to be specified.
. `/var/lib/couchbase/backups` is the directory where backup will be stored
. `-u` option is used to specify the admin user name
. `-p` option is used to specify the admin password
. `-b` option is used to specify the bucket name, `twitter` in this case

The first run of this command will perform a full backup because `/var/lib/couchbase/backups/` directory is empty to begin with. Subsequent runs of this command will perform incremental backups.

== Backup all buckets in cluster

Backup all buckets in an entire cluster. This is the default option when no bucket is specified.

```
/opt/couchbase/bin/cbbackup \
    http://<any-node-ip>:8091 \
    /var/lib/couchbase/backups/ \
    -u Administrator \
    -p password
```

== Back up all buckets on a single node

Backup all buckets on a single node in cluster by using `--single-node` option.

```
/opt/couchbase/bin/cbbackup \
    http://<single-node-ip>:8091 \
    /var/lib/couchbase/backups/ \
    -u Administrator \
    -p password \
    --single-node
```

== Backup one bucket on a specified node

Backup one named bucket on a specified node

```
/opt/couchbase/bin/cbbackup \
    http://<single-node-ip>:8091 \
    /var/lib/couchbase/backups/ \
    -u Administrator \
    -p password \
    --single-node \
    -b <bucket>
```

Full, incremental and cumulative backups can be performed using `-m` option.

Complete details about the `cbbackup` command, including all the options, are explained at https://developer.couchbase.com/documentation/server/current/cli/cbbackup-tool.html.

== Optional Upload to S3

Keeping the backup data on the same host introduces a Single Point of Failure. Its recommended to save the backup data on a remote drive, such as S3.

Create a zipped archive of the backup tagged by year, month, day, hour, minute and seconds. Upload the archive to S3:

```
filename=twitter-backups-`date +%Y-%m-%d-%H-%M-%S`.tar.gz
sudo tar czvf $filename /var/lib/couchbase/backups/
s3cmd put $filename s3://arungupta.me/
```

More details about downloading, installing and configuring `s3cmd` are available at http://s3tools.org/s3cmd.

Add these commands in a script. Copy that script in `/etc/cron.daily` directory to set it up as a daily cron job. This script may be copied to `/etc/cron.hourly` for hourly backups. https://help.ubuntu.com/community/CronHowto[CronHowTo] explain other configuration options to configure cron on Ubuntu.

